language: node_js
node_js:
  - 10

jobs:
  include:
    - stage: test
      name: "Test"
      script: yarn test

    - stage: deploy
      name: "Deploy"
      script: skip
      deploy:
        provider: heroku
        app: fin-track-api
        api_key:
          secure: BCAaWoLLWKQWnxDU3lyF3HLbF7OcCZu+KLf77fgZBgIhkCyQpx+oT1slEiu7oP/mEQ4rXY3BBW7ENJ6BcUxTMDJMQvqHe1mzMVke0EckAawDCICd9JNHVS0wS159tq1EeB6Y4dW+eK21lDMm1C552BBrd2MB3n8HeV8rxWBzPfhaqDv1Y8SD7azLfDR1Wc6owjJHzBC3OHPbft9Tu7dDoiSR9AvHY8bcnwDLcspwodUBYd+gTwAWbPBA0T5KczuHOp94WGQYOLyFQLBguqUsskDRhWciieTbnDILMCkg+DMzscM7nBiqdS/gysSFRtmL2xnyI0Af26IEHP6P4FAtJc02KVcMhJLjxqfEqxODKhOAqyo64NkUA9jyOLxvK/OPAnlzndNnOG3V6rLDorY+iNiN+CqlIT1VxRXo8ilyPV+ZDaDzPTJG6/+2kOVPWT7fwTVFBNFnqlTjBI5ktUas8HqPB6gZgpai+l4IAQK7OJOshhZ6PplAeLprH5B+hv8yH36MFBvqDFD0dPXe9iJ6muA9EnRbwzPWY6vRM+FQcZ26Y2NHxotdAyFsV78JRgehvXPbnhCc2IoHTXikGoQJFFPGsXtT54aN6YEkAWkj7E+rCEVtu40P+b48DunsrHPhX8dBhYqRN2owPYlWUmINXJ6AIOjdf71akge0tgoEU4I=
