language: node_js
node_js:
  - 12
jobs:
  include:
    - stage: test
      name: Test
      script: yarn test
    - stage: deploy
      name: Deploy
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: hOQFL+zr40ooe/plI8lGY/7HPa4WsZyHeNzlNSng9KS09HE/zQHR9JdrWqVFcxeSCr/8SV5d4viJ9kvtpwcE6GjrcQx/SHYxXJk15ePUnEKrHbmHZwYmZFHL0kgHg0aF7S4/NaCLP9VaqhsHR2YtYs+vX0If/6/+yGaGHML9NZ2dZ/8o7/OrB8QElR+JIjKkckJgWaWnvEoC2nZhFNSQD17NrP0x+VF4vOByhpfsFVtmcJpqWXWIDKsV32jy0H1AiI+XLprntYFhOdG85b4oIJ8nI4XBJnxeoqtNUueQcXtGslCZ5J0UlY5qxnUp00WHy/0r8axMeqKJI5HHgbKrTFnhHpSX8BeEI8XeM93XH6YTuudFzvfWa5GYwxA2hG3kDMOp1WdSdQVl01AWwNNqpNLDeZfJFBwn1cmKweLaMVewffb763sB1pPcPdYwyLGOo+TjwdnoDuNTR1PfBE7fvh3Ca/7aQEdiArNtrRziLpdBxSkF23Pw7zz4BbsLjUmFmsnBgcpJIziaAr+xlXNf4EkuSccfNpIdoG8qQ6YOM9xIWwgMX2DGDFui24UagSdF6SIIAo6WjhpPMJ+xVYamgIai0PjaPqBhVPNUlR2nUVaFgb/7Zq7qqFZCaGo+RMnBEwmgWWxHu8BJN/Je4RiEgJkNVH77wEFLlkDUOFUr4rw=
        app: fin-track-api
        on:
          repo: klubiniecki/fin-api
